import rospy

nlp_knowledge_map = {
    "_COMMENTS":{
        "Designedchair":"nur chair, nicht designed",
        "Designedhandle":"nur handle",
        "Washer":"Scheibe, nicht spülmaschine",
        "Milkbottle":"milk ist hier nicht milk bottle sondern milk pack",
        "Milkpackja":"was ist das"
    },
    "Trashbin":["trash bin", "trash can"],
    "Plasticknife":["plastic knife"],
    "Designedchair":["chair"],
    "Cupboard":["cupboard"],
    "Foambrick":["foam brick"],
    "Fork":["fork"],
    "Spatula":["spatula"],
    "Pitcher":["pitcher"],
    "Bleachcleanserbottle":["bleach cleanser bottle"],
    "Kitchencabinet":["cabinet", "kitchen cabinet"],
    "Crackerbox":["cracker box", "crackers"],
    "Minisoccerball":["mini soccer ball"],
    "Baseball":["baseball"],
    "Tablecloth":["table cloth"],
    "Washer":["washer"],
    "Designedhandle":["handle"],
    "Pot":["pot"],
    "Napkin":["napkin"],
    "Mustardbottle":["mustard bottle", "mustard container", "mustard"],
    "Jellochocolatepuddingbox":["jello chocolate pudding box"],
    "Door":["door"],
    "Servingmat":["serving mat"],
    "Dishwasher":["dishwasher"],
    "Naturalperson":["her", "him", "them", "Alice", "Adel", "Amanda", "Andrew", "Angel", "Ashley", "Axel", "Bob", "Brittany", "Charlie", "Christopher", "Daniel", "David", "Elizabeth", "James", "Jane", "Jennifer", "Jessica", "John", "Joseph", "Joshua", "Jules", "Justin", "Lauren", "Matthew", "Michael", "Morgan", "Paris", "Robin", "Simone", "Samantha", "Sarah", "Stephanie"],
    "Wineglass":["wine glass", "glass of wine"],
    "Shelf":["shelf"],
    "Tray":["tray"],
    "Orange":["orange"],
    "Table":["table"],
    "Bowl":["bowl"],
    "Glass":["glass"],
    "Coffeepack":["coffee pack"],
    "Golfball":["golf ball"],
    "Softball":["softball"],
    "Saltshaker":["salt", "salt shaker"],
    "Metalplate":["metal plate"],
    "Pringleschipscan":["pringles chips can"],
    "Strawberry":["strawberry"],
    "Glasscleanerspraybottle":["glass cleaner spray bottle"],
    "Tennisball":["tennis ball"],
    "Spoon":["spoon"],
    "Marble":["marble"],
    "Bottle":["bottle"],
    "Metalmug":["metal mug"],
    "Rope":["rope"],
    "Stackingblocks":["stacking blocks"],
    "Abrasivesponge":["abrasive sponge"],
    "Racquetball":["racquetball"],
    "Jellobox":["jello box"],
    "Dishwashertab":["dishwasher tab"],
    "Knife":["knife"],
    "Plasticchain":["plastic chain"],
    "Plate":["plate"],
    "Cup":["cup"],
    "Dice":["dice"],
    "Cerealbox":["box of cereal", "cereal box"],
    "Metalbowl":["metal bowl"],
    "Sugarbox":["box of sugar", "sugar box", "sugar"],
    "Skillet":["skillet"],
    "Kiwi":["kiwi"],
    "Drawer":["drawer"],
    "Toyotahsr":["toyota hsr"],
    "Coffeecan":["coffee can", "can of coffee"],
    "Milkpack":["milk pack", "milk"],
    "Toothpaste":["toothpaste"],
    "Oreganoshaker":["oregano shaker"],
    "Apple":["apple"],
    "Tomatosoupcan":["tomato soup can", "can of tomato soup"],
    "Tunafishcan":["tuna fish can", "can of tuna fish"],
    "Bag":["bag"],
    "Juicebox":["juicebox"],
    "Pancakemixbottle":["bottle of pancake mix", "pancake mix bottle"],
    "Jellostrawberrybox":["jello strawberry box"],
    "Teabagbox":["tea bag box", "box of tea bags"],
    "Pastrybox":["pastry box"],
    "Pear":["pear"],
    "Lemon":["lemon"],
    "Banana":["banana"],
    "Pottedmeatcan":["potted meat can", "can of potted meat"],
    "Peach":["peach"],
    "Plum":["plum"],
    "Winebottle":["wine bottle", "bottle of wine"],
    "Juicepack":["juice pack", "pack of juice"],
    "Colacan":["cola can", "cola", "coke", "can of coke"],
    "Tropicaljuicebottle":["bottle of tropical juice", "tropical juice bottle"],
    "Milkbottle":["milk bottle", "bottle of milk"],
    "Iceteabottle":["ice tea bottle", "bottle of ice tea"],
    "Orangejuicebox":["orange juice box", "orange juice", "box of orange juice"],
    "Rubikscube":["rubiks cube"],
    "Cerealboxrobocup":["cereal box robo cup"],
    "Nesquickcerealbox":[],
    "Milkpackja":[],
    "Mueslibox":[],
    "Stapelchips":["chips can"],
    "Cupblue":[],
    "Cupgreen":[],
    "Largemarker":["marker"],
    "Masterchefcan":[],
    "Scissors":["scissors"],
    "Scrubcleaner":["scrub cleaner"],
    "Grapes":["grapes"],
    "Cupsmall":[],
    "Screwdriver":["screwdriver"],
    "Clamp":["clamp"],
    "Hammer":["hammer"],
    "Woodblock":["wood block", "block of wood"],
    "Cornybox":["corny box", "box of corny"]
}