# trash_bin = 'http://www.ease-crc.org/ont/SUTURO.owl#TrashBin'
# plastic_knife = 'http://www.ease-crc.org/ont/SUTURO.owl#PlasticKnife'
# designed_chair = 'http://www.ease-crc.org/ont/SOMA.owl#DesignedChair'
cupboard = 'http://www.ease-crc.org/ont/SOMA.owl#Cupboard'
# foam_brick = 'http://www.ease-crc.org/ont/SUTURO.owl#FoamBrick'
fork = 'http://www.ease-crc.org/ont/SOMA.owl#Fork'
# spatula = 'http://www.ease-crc.org/ont/SOMA.owl#Spatula'
pitcher = 'http://www.ease-crc.org/ont/SUTURO.owl#Pitcher'
bleach_cleanser_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#BleachCleanserBottle'
kitchen_cabinet = 'http://www.ease-crc.org/ont/SOMA.owl#KitchenCabinet'
cracker_box = 'http://www.ease-crc.org/ont/SUTURO.owl#CrackerBox'
mini_soccer_ball = 'http://www.ease-crc.org/ont/SUTURO.owl#MiniSoccerBall'
baseball = 'http://www.ease-crc.org/ont/SUTURO.owl#Baseball'
# table_cloth = 'http://www.ease-crc.org/ont/SUTURO.owl#TableCloth'
# washer = 'http://www.ease-crc.org/ont/SUTURO.owl#Washer'
# designed_handle = 'http://www.ease-crc.org/ont/SOMA.owl#DesignedHandle'
# pot = 'http://www.ease-crc.org/ont/SOMA.owl#Pot'
# napkin = 'http://www.ease-crc.org/ont/SUTURO.owl#Napkin'
mustard_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#MustardBottle'
jell_ochocolate_pudding_box = 'http://www.ease-crc.org/ont/SUTURO.owl#JellOChocolatePuddingBox'
door = 'http://www.ease-crc.org/ont/SOMA.owl#Door'
# serving_mat = 'http://www.ease-crc.org/ont/SUTURO.owl#ServingMat'
# dishwasher = 'http://www.ease-crc.org/ont/SOMA.owl#Dishwasher'
# natural_person = 'http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#NaturalPerson'
wine_glass = 'http://www.ease-crc.org/ont/SOMA.owl#WineGlass'
shelf_layer = 'http://www.ease-crc.org/ont/SUTURO.owl#ShelfLayer'
# tray = 'http://www.ease-crc.org/ont/SUTURO.owl#Tray'
orange = 'http://www.ease-crc.org/ont/SUTURO.owl#Orange'
table = 'http://www.ease-crc.org/ont/SOMA.owl#Table'
bowl = 'http://www.ease-crc.org/ont/SOMA.owl#Bowl'
# glass = 'http://www.ease-crc.org/ont/SOMA.owl#Glass'
coffee_pack = 'http://www.ease-crc.org/ont/SUTURO.owl#CoffeePack'
# golf_ball = 'http://www.ease-crc.org/ont/SUTURO.owl#GolfBall'
soft_ball = 'http://www.ease-crc.org/ont/SUTURO.owl#SoftBall'
# salt_shaker = 'http://www.ease-crc.org/ont/SOMA.owl#SaltShaker'
metal_plate = 'http://www.ease-crc.org/ont/SUTURO.owl#MetalPlate'
pringles_chips_can = 'http://www.ease-crc.org/ont/SUTURO.owl#PringlesChipsCan'
strawberry = 'http://www.ease-crc.org/ont/SUTURO.owl#Strawberry'
# glass_cleaner_spray_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#GlassCleanerSprayBottle'
tennis_ball = 'http://www.ease-crc.org/ont/SUTURO.owl#TennisBall'
spoon = 'http://www.ease-crc.org/ont/SOMA.owl#Spoon'
# marble = 'http://www.ease-crc.org/ont/SUTURO.owl#Marble'
# bottle = 'http://www.ease-crc.org/ont/SOMA.owl#Bottle'
metal_mug = 'http://www.ease-crc.org/ont/SUTURO.owl#MetalMug'
# rope = 'http://www.ease-crc.org/ont/SUTURO.owl#Rope'
# stacking_blocks = 'http://www.ease-crc.org/ont/SUTURO.owl#StackingBlocks'
abrasive_sponge = 'http://www.ease-crc.org/ont/SUTURO.owl#AbrasiveSponge'
# racquetball = 'http://www.ease-crc.org/ont/SUTURO.owl#Racquetball'
jello_box = 'http://www.ease-crc.org/ont/SUTURO.owl#JelloBox'
dishwasher_tab = 'http://www.ease-crc.org/ont/SOMA.owl#DishwasherTab'
knife = 'http://www.ease-crc.org/ont/SOMA.owl#Knife'
# plastic_chain = 'http://www.ease-crc.org/ont/SUTURO.owl#PlasticChain'
plate = 'http://www.ease-crc.org/ont/SOMA.owl#Plate'

# dice = 'http://www.ease-crc.org/ont/SUTURO.owl#Dice'
cereal_box = 'http://www.ease-crc.org/ont/SOMA.owl#CerealBox'
metal_bowl = 'http://www.ease-crc.org/ont/SUTURO.owl#MetalBowl'
sugar_box = 'http://www.ease-crc.org/ont/SUTURO.owl#SugarBox'
# skillet = 'http://www.ease-crc.org/ont/SUTURO.owl#Skillet'
kiwi = 'http://www.ease-crc.org/ont/SUTURO.owl#Kiwi'
# drawer = 'http://www.ease-crc.org/ont/SOMA.owl#Drawer'
# toyota_hsr = 'http://www.ease-crc.org/ont/SUTURO.owl#ToyotaHSR'
coffee_can = 'http://www.ease-crc.org/ont/SUTURO.owl#CoffeeCan'
#milk_pack = 'http://www.ease-crc.org/ont/SOMA.owl#MilkPack'
# toothpaste = 'http://www.ease-crc.org/ont/SUTURO.owl#Toothpaste'
# oregano_shaker = 'http://www.ease-crc.org/ont/SUTURO.owl#OreganoShaker'
apple = 'http://www.ease-crc.org/ont/SUTURO.owl#Apple'
tomato_soup_can = 'http://www.ease-crc.org/ont/SUTURO.owl#TomatoSoupCan'
tuna_fish_can = 'http://www.ease-crc.org/ont/SUTURO.owl#TunaFishCan'
# bag = 'http://www.ease-crc.org/ont/SUTURO.owl#Bag'
juice_box = 'http://www.ease-crc.org/ont/SUTURO.owl#JuiceBox'
# pancake_mix_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#PancakeMixBottle'
gelatine_box = 'http://www.ease-crc.org/ont/SUTURO.owl#GelatineBox'
#tea_bag_box = 'http://www.ease-crc.org/ont/SUTURO.owl#TeaBagBox'
# pastry_box = 'http://www.ease-crc.org/ont/SUTURO.owl#PastryBox'
pear = 'http://www.ease-crc.org/ont/SUTURO.owl#Pear'
lemon = 'http://www.ease-crc.org/ont/SUTURO.owl#Lemon'
banana = 'http://www.ease-crc.org/ont/SUTURO.owl#Banana'
potted_meat_can = 'http://www.ease-crc.org/ont/SUTURO.owl#PottedMeatCan'
peach = 'http://www.ease-crc.org/ont/SUTURO.owl#Peach'
plum = 'http://www.ease-crc.org/ont/SUTURO.owl#Plum'
wine_bottle = 'http://www.ease-crc.org/ont/SOMA.owl#WineBottle'
# juice_pack = 'http://www.ease-crc.org/ont/SUTURO.owl#JuicePack'

# tropical_juice_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#TropicalJuiceBottle'
milk_bottle = 'http://www.ease-crc.org/ont/SOMA.owl#MilkBottle'

# orange_juice_box = 'http://www.ease-crc.org/ont/SUTURO.owl#OrangeJuiceBox'
rubiks_cube = 'http://www.ease-crc.org/ont/SUTURO.owl#RubiksCube'
# cereal_box_robo_cup = 'http://www.ease-crc.org/ont/SUTURO.owl#CerealBoxRoboCup'
# nesquick_cereal_box = 'http://www.ease-crc.org/ont/SUTURO.owl#NesquickCerealBox'
milk_pack_ja = 'http://www.ease-crc.org/ont/SUTURO.owl#MilkPackJa'
milk = 'http://www.ease-crc.org/ont/SUTURO.owl#MilkPackJa'
milk_pack = 'http://www.ease-crc.org/ont/SUTURO.owl#MilkPackJa'
muesli_box = 'http://www.ease-crc.org/ont/SUTURO.owl#MuesliBox'
stapel_chips = 'http://www.ease-crc.org/ont/SUTURO.owl#StapelChips'
staple_chips = 'http://www.ease-crc.org/ont/SUTURO.owl#StapelChips'

large_marker = 'http://www.ease-crc.org/ont/SUTURO.owl#LargeMarker'
masterchef_can = 'http://www.ease-crc.org/ont/SUTURO.owl#MasterchefCan'
scissors = 'http://www.ease-crc.org/ont/SUTURO.owl#Scissors'
scrub_cleaner = 'http://www.ease-crc.org/ont/SUTURO.owl#ScrubCleaner'
grapes = 'http://www.ease-crc.org/ont/SUTURO.owl#Grapes'
cup = 'http://www.ease-crc.org/ont/SOMA.owl#Cup'
cup_small = 'http://www.ease-crc.org/ont/SUTURO.owl#CupSmall'
cup_blue = 'http://www.ease-crc.org/ont/SUTURO.owl#CupBlue'
cup_green = 'http://www.ease-crc.org/ont/SUTURO.owl#CupGreen'
screw_driver = 'http://www.ease-crc.org/ont/SUTURO.owl#ScrewDriver'
clamp = 'http://www.ease-crc.org/ont/SUTURO.owl#Clamp'
hammer = 'http://www.ease-crc.org/ont/SUTURO.owl#Hammer'
wood_block = 'http://www.ease-crc.org/ont/SUTURO.owl#WoodBlock'
corny_box = 'http://www.ease-crc.org/ont/SUTURO.owl#CornyBox'
sponge = 'http://www.ease-crc.org/ont/SUTURO.owl#Sponge'

wash_cloth = 'http://www.ease-crc.org/ont/SUTURO.owl#WashCloth'
washcloth = 'http://www.ease-crc.org/ont/SUTURO.owl#WashCloth'

soap = 'http://www.ease-crc.org/ont/SUTURO.owl#Soap'
fanta_can = 'http://www.ease-crc.org/ont/SUTURO.owl#FantaCan'
fanta = 'http://www.ease-crc.org/ont/SUTURO.owl#FantaCan'
ice_tea_can = 'http://www.ease-crc.org/ont/SUTURO.owl#IceTeaCan'
ice_tea_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#IceTeaBottle'
ice_tea = 'http://www.ease-crc.org/ont/SUTURO.owl#IceTeaCan'

dubbel_fris = 'http://www.ease-crc.org/ont/SUTURO.owl#DubbelFris'
double_freeze = 'http://www.ease-crc.org/ont/SUTURO.owl#DubbelFris'
double_free = 'http://www.ease-crc.org/ont/SUTURO.owl#DubbelFris'

water_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#WaterBottle'
water = 'http://www.ease-crc.org/ont/SUTURO.owl#WaterBottle'
cola_bottle = 'http://www.ease-crc.org/ont/SUTURO.owl#ColaBottle'
cola = 'http://www.ease-crc.org/ont/SUTURO.owl#Cola'
cola_can = 'http://www.ease-crc.org/ont/SUTURO.owl#ColaCan'
pea_soup_can = 'http://www.ease-crc.org/ont/SUTURO.owl#PeaSoupCan'
pea_soup = 'http://www.ease-crc.org/ont/SUTURO.owl#PeaSoupCan'
cornflakes = 'http://www.ease-crc.org/ont/SUTURO.owl#Cornflakes'


curry = 'http://www.ease-crc.org/ont/SUTURO.owl#Curry'
ketchup = 'http://www.ease-crc.org/ont/SUTURO.owl#Curry'

mayonaise = 'http://www.ease-crc.org/ont/SUTURO.owl#Mayonaise'
mayonnaise = 'http://www.ease-crc.org/ont/SUTURO.owl#Mayonaise'
myonies = 'http://www.ease-crc.org/ont/SUTURO.owl#Mayonaise'
myunays = 'http://www.ease-crc.org/ont/SUTURO.owl#Mayonaise'

hagelslag = 'http://www.ease-crc.org/ont/SUTURO.owl#Hagelslag'
huggle_slug = 'http://www.ease-crc.org/ont/SUTURO.owl#Hagelslag'
huggle_sluck = 'http://www.ease-crc.org/ont/SUTURO.owl#Hagelslag'

sausages = 'http://www.ease-crc.org/ont/SUTURO.owl#Sausages'
pancake_mix = 'http://www.ease-crc.org/ont/SUTURO.owl#PancakeMix'
crisps_bag = 'http://www.ease-crc.org/ont/SUTURO.owl#CrispsBag'
crisps = 'http://www.ease-crc.org/ont/SUTURO.owl#CrispsBag'

candy = 'http://www.ease-crc.org/ont/SUTURO.owl#Candy'


stroopwafels = 'http://www.ease-crc.org/ont/SUTURO.owl#Stroopwafels'
# alternatives:
stroke_waffle = 'http://www.ease-crc.org/ont/SUTURO.owl#Stroopwafels'
struck_waffles = 'http://www.ease-crc.org/ont/SUTURO.owl#Stroopwafels'
stroke_waffles = 'http://www.ease-crc.org/ont/SUTURO.owl#Stroopwafels'


liquorice = 'http://www.ease-crc.org/ont/SUTURO.owl#Liquorice'
light_degrees = 'http://www.ease-crc.org/ont/SUTURO.owl#Liquorice'

tic_tac = 'http://www.ease-crc.org/ont/SUTURO.owl#TicTac'
tick_tacks = 'http://www.ease-crc.org/ont/SUTURO.owl#TicTac'
tick_tack = 'http://www.ease-crc.org/ont/SUTURO.owl#TicTac'
take_tack = 'http://www.ease-crc.org/ont/SUTURO.owl#TicTac'

candle = 'http://www.ease-crc.org/ont/SUTURO.owl#Candle'
grocery_bag = 'http://www.ease-crc.org/ont/SUTURO.owl#GroceryBag'
# Furniture
# hallway_cabinet = 'http://www.ease-crc.org/ont/SUTURO.owl#HallwayCabinet'
# shelf = 'http://www.ease-crc.org/ont/SUTURO.owl#Shelf'
# coat_hanger = 'http://www.ease-crc.org/ont/SUTURO.owl#CoatHanger'
# tv_table = 'http://www.ease-crc.org/ont/SUTURO.owl#TvTable'
# lounge_chair = 'http://www.ease-crc.org/ont/SUTURO.owl#LoungeChair'
# lamp = 'http://www.ease-crc.org/ont/SUTURO.owl#Lamp' # fehlt in KB
# couch = 'http://www.ease-crc.org/ont/SUTURO.owl#Couch'
# coffee_table = 'http://www.ease-crc.org/ont/SUTURO.owl#CoffeeTable'
# trashcan = 'http://www.ease-crc.org/ont/SUTURO.owl#TrashCan'
# kitchen_cabinet = 'http://www.ease-crc.org/ont/SUTURO.owl#KitchenCabinet'
# dinner_table = 'http://www.ease-crc.org/ont/SUTURO.owl#DinnerTable'
# dishwasher = 'http://www.ease-crc.org/ont/SUTURO.owl#Dishwasher'
# kitchen_counter = 'http://www.ease-crc.org/ont/SUTURO.owl#KitchenCounter'
